services:
  backend:
    restart: unless-stopped   
    build:  
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    environment:
      - NODE_ENV=production
    volumes:
      - ./sqlite.db:/app/sqlite.db