services:
  backend:
    restart: unless-stopped   
    build:  
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    environment:
      - NODE_ENV=production
      - BETTER_AUTH_SECRET
      - BETTER_AUTH_URL
      - SQLITE
      - PORT

    volumes:
      - ./data:/app/data