services:
  backend:
    restart: unless-stopped   
    build:  
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PORT
      - SQLITE
      - BETTER_AUTH_SECRET
      - BETTER_AUTH_URL
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - MICROSOFT_CLIENT_ID
      - MICROSOFT_CLIENT_SECRET

    volumes:
      - ./data:/app/data