# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1.2 AS build

# Set the working directory to /app inside the container
WORKDIR /app

# Copy necessary package files to install dependencies
COPY package.json package.json
COPY bun.lock bun.lock
COPY drizzle.config.ts drizzle.config.ts

# Install dependencies using Bun
RUN bun install

# Copy source code
COPY ./src ./src

# Start Server
EXPOSE 3000/tcp
CMD ["bun", "dev"]

