name: validation

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Check typescript errors 
        run: bun check

  format:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Check format
        run: bun x @biomejs/biome format src --error-on-warnings

  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Check format
        run: bun x @biomejs/biome lint src --error-on-warnings

  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Copy env file
        run: cp .env.example .env
      - name: Build Docker Images
        run: docker compose -f compose.yaml build